//
//  MTGFileWriter.m
//  ModelToGL
//
//  Created by Harshad on 04/04/2014.
//  Copyright (c) 2014 Laughing Buddha Software. All rights reserved.
//

/*
 This is how triangles are represented
 {vertex1, vertex2, vertex3}
 ==>
 {{vertex1.position, vertex1.tex, vertex1.normal}, {vertex2.position, vertex2.tex, vertex2.normal}, {vertex3.position, vertex3.texture, vertex3.normal}}
 ==>
 {{{x1, y1, z1}, {s1, t1}, {xn1, yn1, zn1}}, {{x2, y2, z3}, {s2, t2}, {xn2, yn2, zn2}}, {{x3, y3, z3}, {s3, t3}, {xn3, yn3, zn3}}}
 */


#import "MTGFileWriter.h"

@implementation MTGFileWriter {
    NSURL *_outputURL;
    int _totalTriangles;
    NSString *_fileName;
    NSURL *_headerURL;
    NSURL *_implementationURL;
    NSURL *_definesHeaderURL;
}

- (instancetype)initForWritingToFileAtURL:(NSURL *)outputURL fileName:(NSString *)fileName {
    self = [super init];
    if (self != nil) {
        _outputURL = [outputURL copy];
        _fileName = [fileName copy];
        NSString *headerPath = [[outputURL path] stringByAppendingPathComponent:[NSString stringWithFormat:@"%@.h", fileName]];
        NSString *implementationPath = [[outputURL path] stringByAppendingPathComponent:[NSString stringWithFormat:@"%@.m", fileName]];
        NSString *definesPath = [[outputURL path] stringByAppendingPathComponent:[NSString stringWithFormat:@"MTGTypes.h"]];
        _headerURL = [NSURL fileURLWithPath:headerPath];
        _implementationURL = [NSURL fileURLWithPath:implementationPath];
        _definesHeaderURL = [NSURL fileURLWithPath:definesPath];
    }

    return self;
}

- (void)writeTriangles:(MTGSceneTriangle *)triangles totalTriangles:(int)totalTriangles {
    _totalTriangles = totalTriangles;
    [self writeTypes];

    NSMutableString *triangleRepresentation = [[NSMutableString alloc] initWithFormat:@"//\n// Generated by ModelToGL:\n// https://github.com/WickedLynx/ModelToGL\n//\n\n#import \"%@\"\n\nMTGSceneTriangle const %@Triangles[%d] = {\n", [_headerURL lastPathComponent], _fileName, _totalTriangles];

    for (int triangleIndex = 0; triangleIndex != totalTriangles; ++triangleIndex) {
        
        MTGSceneTriangle currentTriangle = triangles[triangleIndex];
        
        [triangleRepresentation appendFormat:@"{\n"];
        for (int vertexIndex = 0; vertexIndex != 3; ++vertexIndex) {
            MTGSceneVertex currentVertex = currentTriangle.vertices[vertexIndex];
            [triangleRepresentation appendFormat:@"\t(MTGSceneVertex){{%f, %f, %f}, {%f, %f}, {%f, %f, %f}}", currentVertex.position.x, currentVertex.position.y, currentVertex.position.z, currentVertex.texture.s, currentVertex.texture.t, currentVertex.normal.x, currentVertex.normal.y, currentVertex.normal.z];
            if (vertexIndex < 2) {
                [triangleRepresentation appendFormat:@","];
            }
            [triangleRepresentation appendFormat:@"\n"];
        }
        [triangleRepresentation appendFormat:@"}"];
        if (triangleIndex < totalTriangles -1) {
            [triangleRepresentation appendFormat:@","];
        }
        [triangleRepresentation appendFormat:@"\n"];
    }
    
    [triangleRepresentation appendFormat:@"};"];
    
    [triangleRepresentation writeToURL:_implementationURL atomically:YES encoding:NSUTF8StringEncoding error:nil];

}

- (void)writeTypes {

    NSMutableString *typesHeader = [NSMutableString stringWithFormat:@"//\n// Generated by ModelToGL:\n// https://github.com/WickedLynx/ModelToGL\n//\n\n#import <Foundation/Foundation.h>\n#import <GLKit/GLKit.h>\n\n"];
    [typesHeader appendFormat:@"typedef struct {\n\tGLKVector3 positions;\n\tGLKVector2 texels;\n\tGLKVector3 normals;\n} MTGSceneVertex;"];
    [typesHeader appendFormat:@"\n\n"];
    [typesHeader appendFormat:@"typedef struct {\n\tMTGSceneVertex vertices[3];\n} MTGSceneTriangle;"];

    [typesHeader appendFormat:@"\n\n"];

    [typesHeader writeToURL:_definesHeaderURL atomically:YES encoding:NSUTF8StringEncoding error:nil];

    NSMutableString *modelHeader = [NSMutableString stringWithFormat:@"//\n// Generated by ModelToGL:\n// https://github.com/WickedLynx/ModelToGL\n//\n\n#import \"MTGTypes.h\"\n\n"];

    [modelHeader appendFormat:@"extern MTGSceneTriangle const %@Triangles[%d];", _fileName, _totalTriangles];

    [modelHeader writeToURL:_headerURL atomically:YES encoding:NSUTF8StringEncoding error:nil];




}

@end
