//
// Generated by ModelToGL:
// https://github.com/WickedLynx/ModelToGL
//

#import <Foundation/Foundation.h>
#import <GLKit/GLKit.h>

typedef struct {
	GLKVector3 positions;
	GLKVector2 texels;
	GLKVector3 normals;
} MTGSceneVertex;

typedef struct {
	MTGSceneVertex vertices[3];
} MTGSceneTriangle;

